// Copyright (c) Google Inc. 2011
// All rights reserved.
// This file is automatically generated by GRIT. Do not edit.

#pragma once

#include <atlres.h>

#define IDR_HELLP_WORLD 500
#define IDS_HELLO_WROLD 1000
